config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get "restaurants", to: "restaurants#index"
  # get "restaurants/new", to: "restaurants#new"
  # post "restaurants", to: "restaurants#create"
  # get "restaurants/:id", to: "restaurants#show", as: :restaurant
  # get "restaurants/:id/edit", to: "restaurants#edit", as: :edit
  # patch "restaurants/:id", to: "restaurants#update"
  # delete "restaurants/:id", to: "restaurants#destroy"

  resources :restaurants do
    resources :reviews
    # resources :reviews, only: [ :index, :new, :create]
  end
  # resources :reviews, only: [ :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :category, allow_blank: false, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant_reviewed = Restaurant.find(params[:restaurant_id])
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = @restaurant_reviewed
    @review.save
    redirect_to(restaurant_path(@restaurant_reviewed))
  end

  # def show
    # maybe show the review on the restaurant page so we use that view
  # end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit your Restaurant:</h1>

<%= form_for(@restaurant) do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %>

  <%= t.label :address %>
  <%= t.text_field :address %>

  <%= t.label :phone_number %>
  <%= t.text_field :phone_number %>

  <%= t.label :category %>
  <%= t.select :category, %w(chinese italian japanese french belgian) %>

  <%= t.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<% @restaurants.each do |restaurant|  %>
  <h2><%= link_to restaurant.name, restaurant_path(restaurant)%></h2>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.category%></p>
  <p><%= link_to "Review this restaurant", new_restaurant_review_path(restaurant.id)%></p>
<% end  %>
<br>

<%= link_to "Add a new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add a new Restaurant:</h1>

<%= form_for(@restaurant) do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %>

  <%= t.label :address %>
  <%= t.text_field :address %>

  <%= t.label :phone_number %>
  <%= t.text_field :phone_number %>

  <%= t.label :category %>
  <%= t.select :category, %w(chinese italian japanese french belgian) %>

  <%= t.submit %>
<% end %>
<br>
<%= link_to "Back to restaurants", restaurants_path %>

app/views/restaurants/show.html.erb
<h1>Restaurant: <%= @restaurant.name %></h1>

<p>Description:
  <%= @restaurant.address %>
  <%= @restaurant.phone_number %>
  <%= @restaurant.category %>
</p>

<h4>Reviews:</h4>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <%=  "#{review.rating}: #{review.content}" %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to restaurants", restaurants_path %>
<br>
<br>
<%= link_to "Edit my restaurant", edit_restaurant_path %>
<br>
<br>
<%= link_to "Delete my restaurant", restaurant_path(@restaurant), method: :delete %>

app/views/reviews/new.html.erb
<h1>Review for the restaurant</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add the review", class: "btn btn-primary" %>
<% end %>